package com.smartroute.model;

// Generated 17.11.2012 01:35:47 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Finalassignment generated by hbm2java
 */
@Entity
@Table(name = "finalassignment", catalog = "LkwSchedulerDB")
public class FinalAssignment implements java.io.Serializable {
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(unique = true, nullable = false)
	private Long id;

	@Column(name = "orderIdFin", nullable = false)
	@OneToOne	
	private Contract contract;
	
	@Column(name = "vehicleIdFin", nullable = false)	
	private int vehicleIdFin;

	private TentativeAssignment tentativeAssignment;

	@Column(length = 10)
	private String status;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusChange", nullable = false, length = 19)	
	private Date statusChange;

	public FinalAssignment() {
	}

	public FinalAssignment(Contract contract, int vehicleIdFin, Date statusChange) {
		this.contract = contract;
		this.vehicleIdFin = vehicleIdFin;
		this.statusChange = statusChange;
	}

	public FinalAssignment(Contract contract, int vehicleIdFin,
			TentativeAssignment tentativeAssignmentId, String status, Date statusChange) {
		this.contract = contract;
		this.vehicleIdFin = vehicleIdFin;
		this.tentativeAssignment = tentativeAssignmentId;
		this.status = status;
		this.statusChange = statusChange;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Contract getContract() {
		return this.contract;
	}

	public void setOrderIdFin(Contract contract) {
		this.contract = contract;
	}

	public int getVehicleIdFin() {
		return this.vehicleIdFin;
	}

	public void setVehicleIdFin(int vehicleIdFin) {
		this.vehicleIdFin = vehicleIdFin;
	}

	public TentativeAssignment getTentativeAssignment() {
		return this.tentativeAssignment;
	}

	public void setTentativeAssignmentId(TentativeAssignment tentativeAssignment) {
		this.tentativeAssignment = tentativeAssignment;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getStatusChange() {
		return this.statusChange;
	}

	public void setStatusChange(Date statusChange) {
		this.statusChange = statusChange;
	}

}
