package com.smartroute.model;

// Generated 17.11.2012 01:35:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Routestation generated by hbm2java
 */
@Entity
@Table(name = "routestation", catalog = "LkwSchedulerDB")
public class Routestation implements java.io.Serializable {

	private Integer id;
	private int routeId;
	private byte numberInSequence;
	private Integer contractStation;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private String kind;
	private Date timeFrom;
	private Date timeUntil;
	private Integer leftKg;
	private BigDecimal leftM3;
	private Short leftUnits;

	public Routestation() {
	}

	public Routestation(int routeId, byte numberInSequence) {
		this.routeId = routeId;
		this.numberInSequence = numberInSequence;
	}

	public Routestation(int routeId, byte numberInSequence,
			Integer contractStation, BigDecimal latitude, BigDecimal longitude,
			String kind, Date timeFrom, Date timeUntil, Integer leftKg,
			BigDecimal leftM3, Short leftUnits) {
		this.routeId = routeId;
		this.numberInSequence = numberInSequence;
		this.contractStation = contractStation;
		this.latitude = latitude;
		this.longitude = longitude;
		this.kind = kind;
		this.timeFrom = timeFrom;
		this.timeUntil = timeUntil;
		this.leftKg = leftKg;
		this.leftM3 = leftM3;
		this.leftUnits = leftUnits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "routeId", nullable = false)
	public int getRouteId() {
		return this.routeId;
	}

	public void setRouteId(int routeId) {
		this.routeId = routeId;
	}

	@Column(name = "numberInSequence", nullable = false)
	public byte getNumberInSequence() {
		return this.numberInSequence;
	}

	public void setNumberInSequence(byte numberInSequence) {
		this.numberInSequence = numberInSequence;
	}

	@Column(name = "contractStation")
	public Integer getContractStation() {
		return this.contractStation;
	}

	public void setContractStation(Integer contractStation) {
		this.contractStation = contractStation;
	}

	@Column(name = "latitude", precision = 8, scale = 6)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 8, scale = 6)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "kind", length = 7)
	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timeFrom", length = 19)
	public Date getTimeFrom() {
		return this.timeFrom;
	}

	public void setTimeFrom(Date timeFrom) {
		this.timeFrom = timeFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timeUntil", length = 19)
	public Date getTimeUntil() {
		return this.timeUntil;
	}

	public void setTimeUntil(Date timeUntil) {
		this.timeUntil = timeUntil;
	}

	@Column(name = "leftKg")
	public Integer getLeftKg() {
		return this.leftKg;
	}

	public void setLeftKg(Integer leftKg) {
		this.leftKg = leftKg;
	}

	@Column(name = "leftM3", precision = 5, scale = 3)
	public BigDecimal getLeftM3() {
		return this.leftM3;
	}

	public void setLeftM3(BigDecimal leftM3) {
		this.leftM3 = leftM3;
	}

	@Column(name = "leftUnits")
	public Short getLeftUnits() {
		return this.leftUnits;
	}

	public void setLeftUnits(Short leftUnits) {
		this.leftUnits = leftUnits;
	}

}
