package com.smartroute.model;

// Generated 17.11.2012 01:35:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Suggestion generated by hbm2java
 */
@Entity
@Table(name = "suggestion", catalog = "LkwSchedulerDB")
public class Suggestion implements java.io.Serializable {

	private Integer id;
	private Date schedulerStarted;
	private Byte subNumber;

	public Suggestion() {
	}

	public Suggestion(Date schedulerStarted, Byte subNumber) {
		this.schedulerStarted = schedulerStarted;
		this.subNumber = subNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "schedulerStarted", length = 19)
	public Date getSchedulerStarted() {
		return this.schedulerStarted;
	}

	public void setSchedulerStarted(Date schedulerStarted) {
		this.schedulerStarted = schedulerStarted;
	}

	@Column(name = "subNumber")
	public Byte getSubNumber() {
		return this.subNumber;
	}

	public void setSubNumber(Byte subNumber) {
		this.subNumber = subNumber;
	}

}
