package com.smartroute.model;

// Generated 17.11.2012 01:35:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tentativeassignment generated by hbm2java
 */
@Entity
@Table(name = "tentativeassignment", catalog = "LkwSchedulerDB")
public class TentativeAssignment implements java.io.Serializable {

	private Integer id;
	private int suggId;
	private int orderId;
	private int vehicleId;
	private String status;
	private Date statusChange;

	public TentativeAssignment() {
	}

	public TentativeAssignment(int suggId, int orderId, int vehicleId,
			Date statusChange) {
		this.suggId = suggId;
		this.orderId = orderId;
		this.vehicleId = vehicleId;
		this.statusChange = statusChange;
	}

	public TentativeAssignment(int suggId, int orderId, int vehicleId,
			String status, Date statusChange) {
		this.suggId = suggId;
		this.orderId = orderId;
		this.vehicleId = vehicleId;
		this.status = status;
		this.statusChange = statusChange;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "suggId", nullable = false)
	public int getSuggId() {
		return this.suggId;
	}

	public void setSuggId(int suggId) {
		this.suggId = suggId;
	}

	@Column(name = "orderId", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "vehicleId", nullable = false)
	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "status", length = 14)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusChange", nullable = false, length = 19)
	public Date getStatusChange() {
		return this.statusChange;
	}

	public void setStatusChange(Date statusChange) {
		this.statusChange = statusChange;
	}

}
