package com.smartroute.model;

// Generated 17.11.2012 01:35:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Truck generated by hbm2java
 */
@Entity
@Table(name = "truck", catalog = "LkwSchedulerDB")
public class Truck implements java.io.Serializable {

	private Integer id;
	private int driverId;
	private Boolean isAvailable;
	private String vehicleModel;
	private String vehicleIdNummer;
	private Short capacityUnits;
	private Integer capacityKg;
	private BigDecimal capacityM3;
	private BigDecimal priceKm;
	private BigDecimal priceHour;
	private String mobile;
	private String addressHome;
	private String zipHome;
	private BigDecimal latHome;
	private BigDecimal longHome;

	public Truck() {
	}

	public Truck(int driverId) {
		this.driverId = driverId;
	}

	public Truck(int driverId, Boolean isAvailable, String vehicleModel,
			String vehicleIdNummer, Short capacityUnits, Integer capacityKg,
			BigDecimal capacityM3, BigDecimal priceKm, BigDecimal priceHour,
			String mobile, String addressHome, String zipHome,
			BigDecimal latHome, BigDecimal longHome) {
		this.driverId = driverId;
		this.isAvailable = isAvailable;
		this.vehicleModel = vehicleModel;
		this.vehicleIdNummer = vehicleIdNummer;
		this.capacityUnits = capacityUnits;
		this.capacityKg = capacityKg;
		this.capacityM3 = capacityM3;
		this.priceKm = priceKm;
		this.priceHour = priceHour;
		this.mobile = mobile;
		this.addressHome = addressHome;
		this.zipHome = zipHome;
		this.latHome = latHome;
		this.longHome = longHome;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "driverId", nullable = false)
	public int getDriverId() {
		return this.driverId;
	}

	public void setDriverId(int driverId) {
		this.driverId = driverId;
	}

	@Column(name = "isAvailable")
	public Boolean getIsAvailable() {
		return this.isAvailable;
	}

	public void setIsAvailable(Boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

	@Column(name = "vehicleModel", length = 150)
	public String getVehicleModel() {
		return this.vehicleModel;
	}

	public void setVehicleModel(String vehicleModel) {
		this.vehicleModel = vehicleModel;
	}

	@Column(name = "vehicleIdNummer", length = 10)
	public String getVehicleIdNummer() {
		return this.vehicleIdNummer;
	}

	public void setVehicleIdNummer(String vehicleIdNummer) {
		this.vehicleIdNummer = vehicleIdNummer;
	}

	@Column(name = "capacityUnits")
	public Short getCapacityUnits() {
		return this.capacityUnits;
	}

	public void setCapacityUnits(Short capacityUnits) {
		this.capacityUnits = capacityUnits;
	}

	@Column(name = "capacityKg")
	public Integer getCapacityKg() {
		return this.capacityKg;
	}

	public void setCapacityKg(Integer capacityKg) {
		this.capacityKg = capacityKg;
	}

	@Column(name = "capacityM3", precision = 5, scale = 3)
	public BigDecimal getCapacityM3() {
		return this.capacityM3;
	}

	public void setCapacityM3(BigDecimal capacityM3) {
		this.capacityM3 = capacityM3;
	}

	@Column(name = "priceKm", precision = 5)
	public BigDecimal getPriceKm() {
		return this.priceKm;
	}

	public void setPriceKm(BigDecimal priceKm) {
		this.priceKm = priceKm;
	}

	@Column(name = "priceHour", precision = 5)
	public BigDecimal getPriceHour() {
		return this.priceHour;
	}

	public void setPriceHour(BigDecimal priceHour) {
		this.priceHour = priceHour;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "addressHome", length = 300)
	public String getAddressHome() {
		return this.addressHome;
	}

	public void setAddressHome(String addressHome) {
		this.addressHome = addressHome;
	}

	@Column(name = "zipHome", length = 10)
	public String getZipHome() {
		return this.zipHome;
	}

	public void setZipHome(String zipHome) {
		this.zipHome = zipHome;
	}

	@Column(name = "latHome", precision = 8, scale = 6)
	public BigDecimal getLatHome() {
		return this.latHome;
	}

	public void setLatHome(BigDecimal latHome) {
		this.latHome = latHome;
	}

	@Column(name = "longHome", precision = 8, scale = 6)
	public BigDecimal getLongHome() {
		return this.longHome;
	}

	public void setLongHome(BigDecimal longHome) {
		this.longHome = longHome;
	}

}
