/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smartroute_util_SchedulerApi */

#ifndef _Included_com_smartroute_util_SchedulerApi
#define _Included_com_smartroute_util_SchedulerApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_smartroute_util_SchedulerApi
 * Method:    fnscheduler
 * Signature: ()I
 */
JNIEXPORT jstring JNICALL Java_com_smartroute_util_SchedulerApi_fnscheduler
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
