/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smartroute_util_SchedulerApi */

#ifndef _Included_com_smartroute_util_SchedulerApi
#define _Included_com_smartroute_util_SchedulerApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_smartroute_util_SchedulerApi
 * Method:    fnTryScheduleFavorable
 *
 */
JNIEXPORT jstring JNICALL Java_com_smartroute_util_SchedulerApi_fnTryScheduleFavorable
  (JNIEnv *, jobject, jintArray, jint);


/*
 * Class:     com_smartroute_util_SchedulerApi
 * Method:    fnTryScheduleFavorable
 *
 */
JNIEXPORT jstring JNICALL Java_com_smartroute_util_SchedulerApi_fnBestAvailable
  (JNIEnv *, jobject, jintArray, jint);


/*
 * Class:     com_smartroute_util_SchedulerApi
 * Method:    fnEstimatePrice
 *
 * @ js
 */
JNIEXPORT jint JNICALL Java_com_smartroute_util_SchedulerApi_fnEstimatePrice
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
