<?php

// Diese Datei stammt ursprünglich von http://files.orkney.jp/pgrouting/sample/pgRouting-sampleapp.tar.bz
// und wurde leicht abgewandelt
dl("php_mapscript.dll");

define("MAPFILE","C:/ms4w/Apache/htdocs/routing/routing_os.map");



if($HTTP_GET_VARS["start"])
  $start=$HTTP_GET_VARS["start"];

if($HTTP_GET_VARS["end"])
  $end=$HTTP_GET_VARS["end"];



$delta=0;

$map_file=MAPFILE;
$map=ms_newMapObj($map_file);

$l=$map->getLayerByName("path");
if($l) {
  if($l && $start!=0 && $end!=0) {
$cx1=3429000;
$cy1=5787000;
$cx2=3444000;
$cy2=5800000;

    if($cx1!=0 && $cy1!=0 && $cx2!=0 && $cy2!=0 && 
       $cx1!=$cx2 && $cy1!=$cy2) {
      $minx = min($cx1,$cx2)-$delta;
      $miny = min($cy1,$cy2)-$delta;
      $maxx = max($cx1,$cx2)+$delta;
      $maxy = max($cy1,$cy2)+$delta;

      $map->setextent($minx,$miny,$maxx,$maxy);

      $rectobj = $map->extent;
      $ll_x = $rectobj->minx;
      $ll_y = $rectobj->miny;
      $ur_x = $rectobj->maxx;
      $ur_y = $rectobj->maxy;


      $sql="the_geom from (select gid, the_geom from ".
	"shortest_path_astar2_as_geometry_internal_id('fridastreets', ".
	$start.", ".$end.", ".$ll_x.", ".$ll_y.", ".$ur_x.", ".
	$ur_y.")) as g using unique gid using SRID=-1";

      $l->set('data', $sql);
      $l->set('status', MS_ON);
					  
    }
  }
  else {
    $l->set('status', MS_OFF);
  }
}
$image=$map->draw();
$image_url=$image->saveWebImage();
echo "<br>";

?>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; UTF-8">
<title>pgRouting mit Freien Geodaten</title>




</head>

<body BGCOLOR="white" TEXT="#000000" LINK="#0000FF" VLINK="#0000FF">
<table width="80%" align="center" border="0">
<tr>
 <td width="550" align=center colspan=2>
    <h2>pgRouting basierend auf den Frida-Daten</h2>
    <h3>Shortest Path mit A*-Algorithmus</h3><br>
</tr>
  <tr> 
    <td>
       <table width="400" border="0" align="right">
	<tr>
	   <td colspan="3" align="right" valign="top">
	      <img src="<?php echo $image_url?>" width="550" height="450" 
                   border="1"><br>
	   </td>
	</tr>

       </table>
    </td>
    <td align="left" valign=top width=200><b><font face="Arial">Startpunkt:</font></b> <br>
 
  <form name="routing" method="get" action="routing_os_frida.phtml">

    <select name=start>
	<option value=0 >W&auml;hle....</option>
<option value=7649 >Dom</option>
	<option value=291 >Im Hone</option>
<option value=7750 >Kolpingstrasse</option>
	<option value=7313 >Martinistr.</option>

		
</select>
    <br><br>

    <b><font face="Arial">Ziel:</font></b><br>
    <select name=end>
    	<option value=0 >W&auml;hle....</option>
			<option value=7720 >Neumarkt</option>
					<option value=2648 >Hunteburger Weg</option>
						<option value=7740 >Johanniskirche</option>
						<option value=4616 >Gruttkamp</option>
		

</select>
    <br><br><br>
    <input type=submit value="Finde Route">
    </td>
  </tr>
</form><tr><td>
<a href="../index.html">Return</a></td></tr>
<tr><td>Quelle von PgRouting: <a href="http://pgrouting.postlbs.org/">http://pgrouting.postlbs.org</a>
</td></tr>
<tr><td>Quelle der Frida-Daten: <a href="http://frida.intevation.org/">http://frida.intevation.org/</a>
</td></tr>
</table>
<br>

</body>
</html>
